### PR TITLE
Added components to PSjira.Project

### PR DESCRIPTION
**Pull request by axxelG**

### CODE REVIEW

**Comment by axxelG** [comment]
`Cannot validate argument on parameter 'NuGetApiKey'. The argument is null or empty.` I think I can't do anything to fix this :-(

**Comment by replicaJunction** [comment]
Sorry about that. You're right - that was an issue with my AppVeyor setup, and I've got that resolved now.

Could you revert the last commit (adding the server to PSJira.Session) in this branch? I see you've got PR #70 open for that, but I'd like to go over that one in a bit more depth before we merge those changes. That way, we can keep that change separate from this one.

Thanks!

**Comment by axxelG** [comment]
I'm on it but quite busy at the moment.

**Comment by axxelG** [comment]
Luckily found some time today. I had to create a new branch and a new merge request: #71

**Comment by axxelG** [comment]
Luckily found some time today. I had to create a new branch and a new merge request: #71 
I submitted the change within this pull request because I thought it will be useful whether the MultiSession-Change would be merged or not. But you are right it's better to keep that together and I'm glad you will review my changes.

btw: Thank you for sharing and maintaining this module!

**Comment by replicaJunction** [comment]
Awesome. Thanks!

**Pull request merged**
