### PR TITLE
Updated Set-JiraIssue to allow for optional Summary and Description

### PR DESCRIPTION
**Pull request by lipkau**
I found in my projects, that often Summary and Descriptions are not mandatory fields

### CODE REVIEW

**Comment by replicaJunction** [comment]
Hi lipkau,

I can understand why Set-JiraIssue may not need Summary and Description to be mandatory, but I'm not sure I understand a use case where New-JiraIssue does not require at least a summary. If you could, would you mind running Get-JiraIssueCreateMetadata and checking to see whether Summary and Description are flagged as Required?

Also, I disagree with your change to Set-JiraConfigServer, as modifying a global variable within the scope of a module is a bad design practice. Users may not want this variable changed, and it would still need to be called each time a user opens a new PowerShell window. You can use New-JiraSession to create a persistent, authenticated session using a cookie, or you can modify the PSDefaultParameterValues variable in your PowerShell profile.

Let me know about those two fields in the create metadata, and if they're not flagged as required, we can adjust the parameter values.

Thanks!
replica

**Comment by lipkau** [comment]
Hi replica.

* I was mistaken with _summary_. I didn't find a project where it is not mandatory.
* _description_ is definitely not always mandatory
* _priority_ is -in my sample- also not mandatory, but the `Set-JiraIssue` fails if I don't provide it.

screenshot_20160404_085453

**Comment by lipkau** [comment]
Regarding the credentials change.

* I didn't mean to place it in the same PR - I forgot to create an extra branch.
* I don't agree that setting defaultParameterValues is a bad practive, as the user can choose if he wants to use it or not (also, I got this idea from several PowerShell MVPs)

**Comment by lipkau** [comment]
Also:
I can set up a 30 day trail JIRA server for you, if you want

**Comment by replicaJunction** [comment]
I'm having some issues with GitHub and pull requests; the updated changes are in branch pr/24 (latest commit 640b3fe). Take a look when you get a chance and see if it matches what you're looking for.

It surprises me that Priority isn't mandatory - I've never seen that before - but I made the change. Now, if you don't supply Priority in a case where it is required, JIRA will send back the same error it would if you omitted another mandatory field.

I don't mean to say that PSDefaultParameterValues is a bad practice in general, but I believe it should be a user-level customization rather than a module-level customization. In my opinion, modifying it in your profile is great, but modules shouldn't mess with your settings. That's just my opinion, though.

Regarding a JIRA trial server - that would be awesome. Would you mind if I drop you an e-mail to discuss further (with the address on your GitHub profile)?

**Comment by lipkau** [comment]
sure. go ahead.
I am also in powershell.slack.com, if you prefer.

**Pull request closed without merging**
