### PR TITLE
Switching to ConvertFrom-Json2

### PR DESCRIPTION
**Pull request by LiamLeane**
OOB ConvertFrom-Json implementation does not allow for overriding JSON
maxlength. Default is easy to exceed with large issue lists.

Change adds a ConvertFrom-Json2 function which allows override of
maxlength, sets the default to Max(int) and replaces all calls to
ConvertFrom-Json with ConvertFrom-Json2

### CODE REVIEW

**Comment by LiamLeane** [comment]
I probably should have run the test suite myself first, works fine with the Jira-Issue but breaks other functions. I blame Friday.

Just updating the code now to play nice. Another commit forthcoming.

**Comment by replicaJunction** [comment]
Hi! Sorry this is a bit delayed; I've had some life changes recently that have affected my ability to work on this.

Your ConvertFrom-Json2 function is super cool (honestly, that was the biggest thing keeping me on PS 3.0; I didn't want to rewrite the JSON cmdlets). Thanks for correcting the Pester test as well.

I don't have the ability to test this live against a JIRA instance right now. Can you confirm that with your change, the module still seems to be performing correctly (creating / resolving / editing issues and such)?

**Comment by LiamLeane** [comment]
Confirming all is working as expected against a live JIRA instance.

On Sun, Apr 3, 2016 at 8:58 PM, Joshua T <notifications@github.com> wrote:

> Hi! Sorry this is a bit delayed; I've had some life changes recently that
> have affected my ability to work on this.
>
> Your ConvertFrom-Json2 function is super cool (honestly, that was the
> biggest thing keeping me on PS 3.0; I didn't want to rewrite the JSON
> cmdlets). Thanks for correcting the Pester test as well.
>
> I don't have the ability to test this live against a JIRA instance right
> now. Can you confirm that with your change, the module still seems to be
> performing correctly (creating / resolving / editing issues and such)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/replicaJunction/PSJira/pull/23#issuecomment-205090481>
>



-- 
*Liam Leane*

Email:      lleane.work@gmail.com
Skype:     lleane.work

**Comment by replicaJunction** [comment]
Great. Thanks for the contribution!

**Pull request merged**
